### ISSUE TITLE
Add smooth scrolling for hashLink

### ISSUE THREAD

**Issue by dzhytomyrsky** [rafrex/react-router-hash-link#4]
Hello, is it possible to add smooth scrolling to hashLink? 

I'm working on project, where we need to use hashLink and it mast move to the linked component without jumping, just smooth scrolling is needed.

**Comment by dzhytomyrsky** [comment]
Tried to add `{behavior: "smooth"}` to options of `scrollIntoView()` it did not work for me

**Comment by rafrex** [comment]
Hi, I had omitted the `scrollIntoView()` options because of the poor support. There was PR #3 that I was open to implementing but the author closed it.

I am open to adding the `scrollIntoView()` options object to the `HashLink` api, so you can pass it in as props, but it would be on you to add the polyfill or not. I don't have an interest in including the polyfill as I want to keep this lib small and focused.

**Comment by rafrex** [comment]
I added `smooth` prop smooth scrolling in `v1.2`, see readme for details.
